services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'delivery_db'
    ports:
      - '3008:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_URL: '${DB_URL}'
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    restart: always